### ISSUE TITLE
Earth demon misprint

### ISSUE THREAD

**Issue by JokeR8552** [CephalofairGames/bnb-rules#3]
Could you add info on earth demon misprint to misprint section?
In the second column it has small rectangle (▯) as usually happens for symbols out of font table.
What should be in place of this symbol, or should we just ignore it?
![image](https://github.com/CephalofairGames/bnb-rules/assets/57179715/2600ec67-cc26-4e17-a708-700855ad9531)

**Comment by CephalofairGames** [comment]
corrected as of 05/08/2024
