### ISSUE TITLE
There is no G icon suppose to show on the card page 25

### ISSUE THREAD

**Issue by tatoMa** [CephalofairGames/bnb-rules#6]
The G icon on the card picture is missing, and I believe the 2 F icons are both wrong, they should be Gs.

![f0a736ccf0d4858e92d4dd16148fa937](https://github.com/CephalofairGames/bnb-rules/assets/12379895/fad9cb49-7c9c-45f3-b859-9b8bd67cee38)

**Comment by CephalofairGames** [comment]
Rather than the diagram missing a G label, the lettered list was mistakenly marking two subbullets as F and adding a superfluous G bullet. Issue has been resolved by fixing the lettered list. Diagram remains unchanged.
